openapi: 3.0.1
info:
  title: Comunidades Ativas API
  description: API para o sistema de comunidades ativas
  version: 1.0.0
  contact:
    name: Suporte
    email: suporte@comunidadesativas.com

servers:
  - url: https://api.comunidadesativas.com/v1
    description: Produção
  - url: https://staging-api.comunidadesativas.com/v1
    description: Homologação
  - url: http://localhost:8000/api/v1
    description: Desenvolvimento Local

# Componentes reutilizáveis
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [user, admin, moderator]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer
        user:
          $ref: '#/components/schemas/User'
    
    Error:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string

# Definição dos caminhos (endpoints)
paths:
  # Autenticação
  /auth/register:
    post:
      tags:
        - Auth
      summary: Registrar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuário registrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/login:
    post:
      tags:
        - Auth
      summary: Fazer login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Credenciais inválidas
  
  /auth/refresh-token:
    post:
      tags:
        - Auth
      summary: Renovar token de acesso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Token renovado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  expiresIn:
                    type: integer
  
  # Usuários
  /users/me:
    get:
      tags:
        - Users
      security:
        - BearerAuth: []
      summary: Obter informações do usuário atual
      responses:
        '200':
          description: Dados do usuário
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Não autorizado
  
  # Ideias
  /ideas:
    get:
      tags:
        - Ideas
      summary: Listar ideias
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, approved, rejected, implemented]
          description: Filtrar por status
      responses:
        '200':
          description: Lista de ideias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Idea'
    
    post:
      tags:
        - Ideas
      summary: Criar nova ideia
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Idea'
      responses:
        '201':
          description: Ideia criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Idea'

# Configurações do API Gateway
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true

x-amazon-apigateway-request-validator: all

x-amazon-apigateway-cors:
  allow_origins:
    - "'*'"
  allow_methods: "'*'"
  allow_headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
  max_age: "'600'"
  allow_credentials: true

x-amazon-apigateway-gateway-responses:
  UNAUTHORIZED:
    statusCode: 401
    responseTemplates:
      application/json: '{"message": $context.error.messageString}'
  BAD_REQUEST:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.validationErrorString}'
  DEFAULT_5XX:
    statusCode: 500
    responseTemplates:
      application/json: '{"message": "Erro interno do servidor"}'
